DROP TABLE IF EXISTS usercart CASCADE;
DROP TABLE IF EXISTS user_demand CASCADE;
DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS product CASCADE;
